In [46]:
import numpy as np  #imports numpy
print(np.identity(3)) #prints a 3x3 identity matrix
print(np.array([(1,0,0),(0,1,0),(0,0,1)])) #prints a 3x3 identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [47]:
import pandas as pd #imports pandas
Fuel_Data1 = pd.DataFrame(pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv', error_bad_lines=False))
print(Fuel_Data1) #prints Fuel_Data1
Fuel_Data1.isnull() # Checks if there are missing values in Fuel_Data1
print(Fuel_Data1.columns[Fuel_Data1.isnull().any()]) # Prints the columns with missing values
Fuel_Data=Fuel_Data1.dropna() # drops the rows with missing values and assigns the new dataframe to Fuel_Data
print(Fuel_Data) #prints Fuel_Data

                      record_id  utility_id_ferc1  report_year  \
0         f1_fuel_1994_12_1_0_7                 1         1994   
1        f1_fuel_1994_12_1_0_10                 1         1994   
2         f1_fuel_1994_12_2_0_1                 2         1994   
3         f1_fuel_1994_12_2_0_7                 2         1994   
4        f1_fuel_1994_12_2_0_10                 2         1994   
5        f1_fuel_1994_12_2_0_13                 2         1994   
6         f1_fuel_1994_12_2_1_1                 2         1994   
7        f1_fuel_1994_12_2_1_10                 2         1994   
8        f1_fuel_1994_12_2_2_10                 2         1994   
9         f1_fuel_1994_12_4_0_1                 4         1994   
10        f1_fuel_1994_12_4_0_2                 4         1994   
11        f1_fuel_1994_12_4_0_4                 4         1994   
12        f1_fuel_1994_12_4_0_5                 4         1994   
13        f1_fuel_1994_12_6_0_1                 6         1994   
14        

                      record_id  utility_id_ferc1  report_year  \
0         f1_fuel_1994_12_1_0_7                 1         1994   
1        f1_fuel_1994_12_1_0_10                 1         1994   
2         f1_fuel_1994_12_2_0_1                 2         1994   
3         f1_fuel_1994_12_2_0_7                 2         1994   
4        f1_fuel_1994_12_2_0_10                 2         1994   
5        f1_fuel_1994_12_2_0_13                 2         1994   
6         f1_fuel_1994_12_2_1_1                 2         1994   
7        f1_fuel_1994_12_2_1_10                 2         1994   
8        f1_fuel_1994_12_2_2_10                 2         1994   
9         f1_fuel_1994_12_4_0_1                 4         1994   
10        f1_fuel_1994_12_4_0_2                 4         1994   
11        f1_fuel_1994_12_4_0_4                 4         1994   
12        f1_fuel_1994_12_4_0_5                 4         1994   
13        f1_fuel_1994_12_6_0_1                 6         1994   
14        

In [48]:
Fuel_Data.describe() #gets a summary description of the dataset (Fuel_Data)
print(Fuel_Data['fuel_qty_burned'].skew()) #prints the skewness of fuel quantity burned
print(Fuel_Data['fuel_qty_burned'].kurt()) #prints the kurtosis of fuel quantity burned

14.152573569147364
587.914076926934


In [49]:
print(Fuel_Data.corr()) #prints the correlation matrix for the dataset (Fuel_Data)

                              utility_id_ferc1  report_year  fuel_qty_burned  \
utility_id_ferc1                      1.000000     0.093267        -0.058025   
report_year                           0.093267     1.000000         0.015894   
fuel_qty_burned                      -0.058025     0.015894         1.000000   
fuel_mmbtu_per_unit                  -0.069000    -0.110421        -0.082971   
fuel_cost_per_unit_burned            -0.037868     0.013495        -0.019147   
fuel_cost_per_unit_delivered         -0.016434    -0.014123        -0.003671   
fuel_cost_per_mmbtu                   0.005884     0.010304        -0.001879   

                              fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
utility_id_ferc1                        -0.069000                  -0.037868   
report_year                             -0.110421                   0.013495   
fuel_qty_burned                         -0.082971                  -0.019147   
fuel_mmbtu_per_unit                    

In [50]:
FCPUD1994 = Fuel_Data[Fuel_Data["report_year"]==[1994]] #This extracts all the entries for the year 1994 from the Fuel_Data
FCPUD1998 = Fuel_Data[Fuel_Data["report_year"]==[1998]] #This extracts all the entries for the year 1998 from the Fuel_Data
print(FCPUD1994)
print(FCPUD1998)
print(len(FCPUD1994))
print(len(FCPUD1998))
# Length of the two are not equal
start_p= FCPUD1994['fuel_cost_per_unit_burned'].mean() #This extracts and gets the mean value for fuel cost per unit burned for the year 1994 from the Fuel_Data and assigns it as the starting point (start_p)
curr_p=FCPUD1998['fuel_cost_per_unit_burned'].mean() #This extracts and gets the mean value for fuel cost per unit burned for the year 1998 from the Fuel_Data and assigns it as the current point (curr_p)
perc_t=((curr_p-start_p)/start_p)*100  #This calculates the percentage increase
print(perc_t)  #This prints the percentage increase.

                    record_id  utility_id_ferc1  report_year  \
0       f1_fuel_1994_12_1_0_7                 1         1994   
1      f1_fuel_1994_12_1_0_10                 1         1994   
2       f1_fuel_1994_12_2_0_1                 2         1994   
3       f1_fuel_1994_12_2_0_7                 2         1994   
4      f1_fuel_1994_12_2_0_10                 2         1994   
5      f1_fuel_1994_12_2_0_13                 2         1994   
6       f1_fuel_1994_12_2_1_1                 2         1994   
7      f1_fuel_1994_12_2_1_10                 2         1994   
8      f1_fuel_1994_12_2_2_10                 2         1994   
9       f1_fuel_1994_12_4_0_1                 4         1994   
10      f1_fuel_1994_12_4_0_2                 4         1994   
11      f1_fuel_1994_12_4_0_4                 4         1994   
12      f1_fuel_1994_12_4_0_5                 4         1994   
13      f1_fuel_1994_12_6_0_1                 6         1994   
14      f1_fuel_1994_12_6_0_2           